export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_MOVIES_THEATRE_REQUEST = 'GET_MOVIES_THEATRE_REQUEST';
export const GET_MOVIES_COMINGSOON_REQUEST = 'GET_MOVIES_COMINGSOON_REQUEST';
export const GET_MOVIES_CHART_REQUEST = 'GET_MOVIES_CHART_REQUEST';

export const GET_MOVIES_GENRES_REQUEST = "GET_MOVIES_GENRES_REQUEST";
export const GET_TV_GENRES_REQUEST = "GET_TV_GENRES_REQUEST";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_FAIL = "GET_GENRES_FAIL";


export const CHANGE_MOVIES_FILTER = "CHANGE_MOVIES_FILTER";


export const GET_NOW_PLAYING_REQUEST = "GET_NOW_PLAYING_REQUEST";
export const GET_UPCOMING_REQUEST = "GET_UPCOMING_REQUEST";
export const GET_UPCOMING_TV_REQUEST = "GET_UPCOMING_TV_REQUEST";
export const GET_TRENDING_REQUEST = "GET_TRENDING_REQUEST";
export const GET_TV_REQUEST = "GET_TV_REQUEST";

