export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_MOVIES_THEATRE_REQUEST = 'GET_MOVIES_THEATRE_REQUEST';
export const GET_MOVIES_COMINGSOON_REQUEST = 'GET_MOVIES_COMINGSOON_REQUEST';
export const GET_MOVIES_CHART_REQUEST = 'GET_MOVIES_CHART_REQUEST';

export const GET_GENRES_REQUEST = "GET_GENRES_REQUEST";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_FAIL = "GET_GENRES_FAIL";

// export const MERGE_GENRES_MOVIES_REQUEST = "MERGE_GENRES_MOVIES_REQUEST";
// export const MERGE_GENRES_MOVIES_SUCCESS = "MERGE_GENRES_MOVIES_SUCCESS";
// export const MERGE_GENRES_MOVIES_FAIL = "MERGE_GENRES_MOVIES_FAIL";

export const CHANGE_MOVIES_FILTER = "CHANGE_MOVIES_FILTER";
